services:
  # Backend API Server
  - type: web
    name: tiktok-coronas-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend Static Site
  - type: web
    name: tiktok-coronas-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://tiktok-coronas-backend.onrender.com